---
roles:
  - name: docker-role
    src: git+https://gitlab.com/ansible-roles8664248/docker-role.git
    scm: git
    version: main

  - name: nginx-role
    src: git+https://gitlab.com/ansible-roles8664248/nginx-role.git 
    scm: git
    version: main